# cypress.yml
name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cypress Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Or your desired version

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          # No need for 'start' or 'wait-on'
          browser: chrome
          record: true 
          command: npm run checkbox-test
        